//! StyxIR → Lean4 emitter module.
//!
//! Reads a `StyxPackage` (deserialized from .styx JSON produced by styx-rustc)
//! and emits Lean4 files in the same format as the LLBC-based emitter.
//! This is the Phase 2 path that eliminates charon_lib.
//!
//! Output format matches the existing generated/LionCore/ files so that
//! correspondence proofs work unchanged.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::emit::indent::IndentWriter;
use crate::ir::*;

mod lookup;
mod types_emit;
mod analysis;
mod desugar;
mod fun_emit;
mod external;
mod body;
mod closures;
mod expr;
mod type_fmt;
mod paths;
mod config;

#[cfg(test)]
mod tests;

pub(crate) use self::lookup::TypeLookup;

// Re-export everything needed by submodules via flat use statements.
// Each submodule imports from siblings explicitly, but these re-exports
// allow `super::*` in submodule files.
pub(crate) use self::lookup::{build_type_lookup, lookup_variant_name, std_enum_variant_name, lookup_field_name};
pub(crate) use self::types_emit::emit_types_file;
pub(crate) use self::analysis::{EmitResult, topo_sort_funs, collect_local_ids, collect_local_ids_in_block, collect_assigned_ids_in_block, collect_assigned_ids_in_expr, collect_local_types, collect_local_types_in_stmt, styx_types_equal, closure_tuple_field_index, is_pure_saturating_num_call};
pub(crate) use self::desugar::{desugar_indexvec, desugar_index_mut_vec, desugar_monadic_dispatch, desugar_pure_arms, desugar_map_err, desugar_try_operators, desugar_get_mut_bind, desugar_free_mut_dup_arm, desugar_index_assign_expr, desugar_uscalar_match, desugar_u64_discriminant_match, desugar_find_closure_compound_bool, desugar_binary_search_if, desugar_binary_search_unit, desugar_revocation_mut_bind, desugar_actor_runtime_if_conditions, desugar_loop_vec_accumulator, insert_bind_before, match_paren_bytes};
pub(crate) use self::fun_emit::emit_funs_file;
pub(crate) use self::external::emit_funs_external;
pub(crate) use self::body::{local_name, set_local_names, set_param_ids, emit_body, emit_block_stmts, emit_block_inline, emit_stmt, emit_expr_lifted, infer_stdlib_type_args, unwrap_ref_type, infer_try_type_args};
pub(crate) use self::closures::{emit_iter_closure_as_do, closure_needs_iter_desugar, closure_body_has_index, emit_option_is_some_and_as_match, emit_option_map_as_match};
pub(crate) use self::expr::{emit_expr, emit_literal, emit_pattern};
pub(crate) use self::type_fmt::{emit_type, extract_type_arg_from_return};
pub(crate) use self::paths::{emit_generics_binder, strip_generics, rust_path_to_lean, is_allocator_type, rust_path_to_lean_type};
pub(crate) use self::config::{contains_unknown_namespace, is_force_opaque, scalar_of_ty, is_unsigned_scalar, is_signed_scalar, scalar_lean_name, scalar_suffix};

/// Emit Lean4 files from a StyxPackage.
pub fn emit_styx_package(
    pkg: &StyxPackage,
    namespace: &str,
    output_dir: &PathBuf,
    aeneas_compat: bool,
    emit_checks: bool,
    skip_stdlib: bool,
) -> BTreeMap<PathBuf, String> {
    let mut files = BTreeMap::new();
    let ns_dir = output_dir.join(namespace);

    let types_content = emit_types_file(pkg, namespace, emit_checks);
    files.insert(ns_dir.join("Types.lean"), types_content);

    let emit_result = emit_funs_file(pkg, namespace, aeneas_compat, emit_checks, skip_stdlib);
    files.insert(ns_dir.join("Funs.lean"), emit_result.funs_lean);

    let ext_content = emit_funs_external(pkg, namespace, &emit_result.sorry_fns, skip_stdlib);
    files.insert(ns_dir.join("FunsExternal.lean"), ext_content.clone());
    files.insert(ns_dir.join("FunsExternal_Template.lean"), ext_content);

    files
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

pub(crate) fn emit_header(w: &mut IndentWriter) {
    w.writeln("-- THIS FILE WAS AUTOMATICALLY GENERATED BY STYX.");
    w.writeln("-- DO NOT EDIT.");
    w.newline();
    w.writeln("import Aeneas");
}

pub(crate) fn emit_options(w: &mut IndentWriter) {
    w.newline();
    w.writeln("set_option linter.dupNamespace false");
    w.writeln("set_option linter.hashCommand false");
    w.writeln("set_option linter.unusedVariables false");
    w.newline();
    w.writeln("open Aeneas.Std Result Error");
}
