//! Direct Rust→Lean emitter (no LLBC/Charon).
//!
//! Reads parsed Rust type definitions and function signatures and emits
//! standalone Lean 4 files:
//!   - Types.lean           — structure, inductive, abbrev declarations
//!   - Funs.lean            — opaque function declarations
//!   - Bridge_Template.lean — correspondence proof outlines (--bridge-template)
//!
//! This is the `--direct` mode emission backend.

use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

use crate::emit::indent::IndentWriter;
use crate::naming::{escape_lean_ident, escape_lean_keyword};
use crate::rust_parser::{
    ParsedCrate, ParsedField, ParsedFnSig, ParsedTypeDef, ParsedTypeKind, ParsedVariant, RustType,
    rust_type_to_lean,
};
use crate::type_rewrite::RewriteRules;

/// Emit Lean 4 files from directly-parsed Rust source.
///
/// Returns a map of output file paths to their contents.
pub fn emit_direct(
    parsed: &ParsedCrate,
    namespace: &str,
    output_dir: &PathBuf,
    emit_checks: bool,
) -> BTreeMap<PathBuf, String> {
    let rules = RewriteRules::standard();
    let mut files = BTreeMap::new();

    let ns_dir = output_dir.join(namespace);

    // Types.lean
    let types_content = emit_types_file(parsed, namespace, &rules, emit_checks);
    files.insert(ns_dir.join("Types.lean"), types_content);

    // Funs.lean (only if there are functions)
    if !parsed.fns.is_empty() {
        let funs_content = emit_funs_file(parsed, namespace, &rules, emit_checks);
        files.insert(ns_dir.join("Funs.lean"), funs_content);
    }

    files
}

// ---------------------------------------------------------------------------
// Types.lean
// ---------------------------------------------------------------------------

fn emit_types_file(
    parsed: &ParsedCrate,
    namespace: &str,
    rules: &RewriteRules,
    emit_checks: bool,
) -> String {
    let mut w = IndentWriter::new();

    // Header
    w.writeln("-- This file was automatically generated by styx (direct mode).");
    w.writeln("-- Do not edit manually.");
    w.newline();
    w.writeln(format!("namespace {namespace}"));
    w.newline();

    // Filter out std/core/alloc types
    let types: Vec<&ParsedTypeDef> = parsed
        .types
        .iter()
        .filter(|t| {
            !t.name.starts_with("std.")
                && !t.name.starts_with("core.")
                && !t.name.starts_with("alloc.")
        })
        .collect();

    if types.is_empty() {
        w.writeln("-- No public types found.");
    }

    for def in &types {
        emit_type_def(&mut w, def, rules, emit_checks);
    }

    w.writeln(format!("end {namespace}"));
    w.finish()
}

/// Emit a single Lean type declaration from a parsed Rust type definition.
fn emit_type_def(
    w: &mut IndentWriter,
    def: &ParsedTypeDef,
    rules: &RewriteRules,
    emit_checks: bool,
) {
    let name = &def.simple_name;

    // Source comment.
    w.writeln(format!("-- Source: {}", def.source_file));

    // Generic params.
    let gp = format_generic_params(&def.type_params);

    match &def.kind {
        ParsedTypeKind::Struct(fields) => {
            emit_struct(w, name, &gp, fields, rules);
        }
        ParsedTypeKind::Enum(variants) => {
            emit_enum(w, name, &gp, variants, rules);
        }
        ParsedTypeKind::Alias(target) => {
            let lean_ty = rust_type_to_lean(target, rules);
            w.writeln(format!("abbrev {name}{gp} := {lean_ty}"));
            w.newline();
        }
    }

    if emit_checks {
        w.writeln(format!("#check @{name}"));
        w.newline();
    }
}

fn emit_struct(
    w: &mut IndentWriter,
    name: &str,
    gp: &str,
    fields: &[ParsedField],
    rules: &RewriteRules,
) {
    if fields.is_empty() {
        // Unit struct.
        w.writeln(format!("structure {name}{gp} where"));
        w.newline();
        return;
    }

    w.writeln(format!("structure {name}{gp} where"));
    w.indent();
    for f in fields {
        let lean_ty = rust_type_to_lean(&f.ty, rules);
        let fname = escape_lean_keyword(&f.name);
        w.writeln(format!("{fname} : {lean_ty}"));
    }
    w.dedent();
    w.newline();
}

fn emit_enum(
    w: &mut IndentWriter,
    name: &str,
    gp: &str,
    variants: &[crate::rust_parser::ParsedVariant],
    rules: &RewriteRules,
) {
    w.writeln(format!("inductive {name}{gp} where"));
    w.indent();
    for v in variants {
        let vname = escape_lean_keyword(&v.name);
        if v.fields.is_empty() {
            w.writeln(format!("| {vname}"));
        } else {
            let args: Vec<String> = v
                .fields
                .iter()
                .map(|f| {
                    let lean_ty = rust_type_to_lean(&f.ty, rules);
                    format!("({} : {})", f.name, lean_ty)
                })
                .collect();
            w.writeln(format!("| {vname} {}", args.join(" ")));
        }
    }
    w.dedent();
    w.newline();
}

// ---------------------------------------------------------------------------
// Funs.lean
// ---------------------------------------------------------------------------

fn emit_funs_file(
    parsed: &ParsedCrate,
    namespace: &str,
    rules: &RewriteRules,
    emit_checks: bool,
) -> String {
    let mut w = IndentWriter::new();

    // Header
    w.writeln("-- This file was automatically generated by styx (direct mode).");
    w.writeln("-- Do not edit manually.");
    w.newline();
    w.writeln(format!("import {namespace}.Types"));
    w.newline();
    w.writeln(format!("namespace {namespace}"));
    w.newline();

    // Group functions by self_type for readability.
    let mut by_type: BTreeMap<Option<String>, Vec<&ParsedFnSig>> = BTreeMap::new();
    for f in &parsed.fns {
        by_type.entry(f.self_type.clone()).or_default().push(f);
    }

    // Emit free functions first.
    if let Some(free_fns) = by_type.remove(&None) {
        w.writeln("-- Free functions");
        w.newline();
        for f in free_fns {
            emit_fn_decl(&mut w, f, rules, emit_checks);
        }
    }

    // Emit method groups.
    for (type_name, methods) in &by_type {
        if let Some(tn) = type_name {
            w.writeln(format!("-- Methods: {tn}"));
            w.newline();
            for m in methods {
                emit_fn_decl(&mut w, m, rules, emit_checks);
            }
        }
    }

    w.writeln(format!("end {namespace}"));
    w.finish()
}

/// Emit a single opaque function declaration.
fn emit_fn_decl(w: &mut IndentWriter, f: &ParsedFnSig, rules: &RewriteRules, emit_checks: bool) {
    let name = &f.name;

    // Source comment.
    w.writeln(format!("-- Source: {}", f.source_file));

    // Generic params.
    let gp = format_generic_params(&f.type_params);

    // Build parameter list (resolve Self to concrete type).
    let params_str = format_params(&f.params, rules, f.self_type.as_deref());

    // Build return type.
    let ret_str = format_return_type(f, rules);

    w.writeln(format!("opaque {name}{gp}{params_str} : {ret_str}"));
    w.newline();

    if emit_checks {
        w.writeln(format!("#check @{name}"));
        w.newline();
    }
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

/// Format generic type parameters for a Lean declaration.
fn format_generic_params(type_params: &[String]) -> String {
    if type_params.is_empty() {
        String::new()
    } else {
        let parts: Vec<String> = type_params
            .iter()
            .map(|p| format!(" ({p} : Type)"))
            .collect();
        parts.join("")
    }
}

/// Format function parameters as Lean syntax.
///
/// If `self_type` is provided, occurrences of `Self` in types are resolved
/// to the concrete type name.
fn format_params(
    params: &[(String, RustType)],
    rules: &RewriteRules,
    self_type: Option<&str>,
) -> String {
    if params.is_empty() {
        return String::new();
    }

    let parts: Vec<String> = params
        .iter()
        .map(|(name, ty)| {
            let lean_ty = resolve_self(&rust_type_to_lean(ty, rules), self_type);
            let escaped = escape_lean_keyword(name);
            format!(" ({escaped} : {lean_ty})")
        })
        .collect();

    parts.join("")
}

/// Format the return type for a function declaration.
///
/// For `&mut self` methods, the return wraps the original return type
/// with the updated self: `Result (ReturnType x SelfType)`.
fn format_return_type(f: &ParsedFnSig, rules: &RewriteRules) -> String {
    let base_ret = resolve_self(
        &rust_type_to_lean(&f.ret_type, rules),
        f.self_type.as_deref(),
    );

    if f.is_mut_self {
        if let Some(ref st) = f.self_type {
            let lean_self = rust_type_to_lean(&RustType::Named(st.clone()), rules);
            // For &mut self methods, return includes updated self.
            // If return is Unit, just return the self type.
            // Otherwise return a product.
            match &f.ret_type {
                RustType::Unit => format!("Result {lean_self}"),
                _ => format!("Result ({base_ret} × {lean_self})"),
            }
        } else {
            format!("Result {base_ret}")
        }
    } else {
        format!("Result {base_ret}")
    }
}

/// Replace `Self` with the concrete type name in a Lean type string.
fn resolve_self(lean_ty: &str, self_type: Option<&str>) -> String {
    match self_type {
        Some(st) => lean_ty.replace("Self", st),
        None => lean_ty.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Bridge template for direct mode
// ---------------------------------------------------------------------------

/// Correspondence proof strength for a directly-parsed type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DirectBridgeKind {
    /// Enum with unit-only constructors → full Equiv (roundtrip proofs).
    Bijective,
    /// Enum with data-carrying constructors → one-way injective.
    Injective,
    /// Struct → relational correspondence (field-by-field Prop structure).
    Relational,
}

/// Classify a `ParsedTypeDef` for bridge correspondence scaffolding.
///
/// Returns `None` for type aliases and unit structs (not interesting for bridges).
fn classify_direct(def: &ParsedTypeDef) -> Option<DirectBridgeKind> {
    match &def.kind {
        ParsedTypeKind::Enum(variants) => {
            if variants.iter().all(|v| v.fields.is_empty()) {
                Some(DirectBridgeKind::Bijective)
            } else {
                Some(DirectBridgeKind::Injective)
            }
        }
        ParsedTypeKind::Struct(fields) => {
            if fields.is_empty() {
                None // Unit struct — skip
            } else {
                Some(DirectBridgeKind::Relational)
            }
        }
        ParsedTypeKind::Alias(_) => None,
    }
}

/// Registry mapping simple type names to their bridge classification.
///
/// Used by `direct_field_correspondence` to emit concrete patterns for
/// nested ADT fields rather than sorry placeholders.
type DirectRegistry = HashMap<String, DirectBridgeKind>;

/// Derive a camelCase function prefix from a simple type name.
/// E.g., `SecurityLevel` → `securityLevel`.
fn derive_prefix(simple_name: &str) -> String {
    if simple_name.is_empty() {
        return "unknown".to_string();
    }
    let mut chars = simple_name.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_lowercase(), chars.as_str()),
        None => "unknown".to_string(),
    }
}

/// Derive a spec type name for a simple extracted type name.
///
/// If `spec_map` contains an entry for `simple_name`, that path is used.
/// Otherwise falls back to `Lion.{simple_name}` with a TODO comment.
fn derive_direct_spec_name(
    simple_name: &str,
    spec_map: Option<&HashMap<String, String>>,
) -> (String, bool) {
    if let Some(map) = spec_map
        && let Some(path) = map.get(simple_name) {
            return (path.clone(), true);
        }
    (format!("Lion.{simple_name}"), false)
}

/// Return true if a `RustType` is a bounded integer scalar (u8…u64, usize, i8…i64, isize).
fn rust_type_is_bounded_scalar(ty: &RustType) -> bool {
    match ty {
        RustType::Named(name) => matches!(
            name.as_str(),
            "u8" | "u16"
                | "u32"
                | "u64"
                | "u128"
                | "usize"
                | "i8"
                | "i16"
                | "i32"
                | "i64"
                | "i128"
                | "isize"
        ),
        _ => false,
    }
}

/// Return true if a `RustType` is `bool`.
fn rust_type_is_bool(ty: &RustType) -> bool {
    matches!(ty, RustType::Named(n) if n == "bool")
}

/// Generate the field equality expression for a struct field in direct mode.
///
/// The `registry` maps simple type names to their `DirectBridgeKind`.
fn direct_field_correspondence(
    field_name: &str,
    ty: &RustType,
    registry: &DirectRegistry,
) -> String {
    let ef = format!("ec.{field_name}");
    let sf = format!("sc.{field_name}");

    // Strip references/pointers transparently.
    let ty = match ty {
        RustType::Ref(inner) | RustType::RawPtr(inner) => inner.as_ref(),
        other => other,
    };

    if rust_type_is_bounded_scalar(ty) {
        // U64 → Nat: extract .val
        format!("{ef}.val = {sf}")
    } else if rust_type_is_bool(ty) {
        format!("{ef} = {sf}")
    } else if matches!(ty, RustType::Named(n) if n == "String" || n == "str") {
        format!("sorry /- TODO: String correspondence for {field_name} -/")
    } else {
        match ty {
            RustType::Generic(base, args) if base == "Option" || base == "core::option::Option" => {
                if let Some(inner_ty) = args.first() {
                    if rust_type_is_bounded_scalar(inner_ty) {
                        return format!("{ef}.map (·.val) = {sf}");
                    }
                    if let RustType::Named(inner_name) = inner_ty
                        && let Some(kind) = registry.get(inner_name.as_str()) {
                            let prefix = derive_prefix(inner_name);
                            match kind {
                                DirectBridgeKind::Bijective | DirectBridgeKind::Injective => {
                                    return format!("{ef}.map {prefix}ToSpec = {sf}");
                                }
                                DirectBridgeKind::Relational => {
                                    return format!(
                                        "sorry /- TODO: Option<{inner_name}> correspondence for {field_name} -/"
                                    );
                                }
                            }
                        }
                }
                format!("{ef} = {sf} -- TODO: verify Option mapping")
            }
            RustType::Generic(base, args)
                if base == "Vec" || base == "alloc::vec::Vec" || base == "std::vec::Vec" =>
            {
                if let Some(inner_ty) = args.first() {
                    if rust_type_is_bounded_scalar(inner_ty) {
                        // Vec<u64> etc. → extract .val on each element
                        return format!("{ef}.map (·.val) = {sf}");
                    }
                    if let RustType::Named(inner_name) = inner_ty
                        && let Some(kind) = registry.get(inner_name.as_str()) {
                            let prefix = derive_prefix(inner_name);
                            match kind {
                                DirectBridgeKind::Bijective | DirectBridgeKind::Injective => {
                                    return format!("{ef}.map {prefix}ToSpec = {sf}");
                                }
                                DirectBridgeKind::Relational => {
                                    let corr = format!("{inner_name}Corresponds");
                                    return format!("List.Forall₂ {corr} {ef} {sf}");
                                }
                            }
                        }
                }
                format!("sorry /- TODO: Vec correspondence for {field_name} -/")
            }
            RustType::Named(type_name) => {
                if let Some(kind) = registry.get(type_name.as_str()) {
                    let prefix = derive_prefix(type_name);
                    match kind {
                        DirectBridgeKind::Bijective | DirectBridgeKind::Injective => {
                            format!("{prefix}ToSpec {ef} = {sf}")
                        }
                        DirectBridgeKind::Relational => {
                            format!("{type_name}Corresponds {ef} {sf}")
                        }
                    }
                } else {
                    // Unknown named type — keep sorry
                    format!("sorry /- TODO: {type_name} correspondence for {field_name} -/")
                }
            }
            _ => format!("{ef} = {sf}"),
        }
    }
}

/// Emit BIJECTIVE correspondence for a unit-only enum.
fn emit_direct_bijective(
    w: &mut IndentWriter,
    name: &str,
    namespace: &str,
    spec: &str,
    spec_known: bool,
    variants: &[ParsedVariant],
) {
    let extracted = format!("{namespace}.{name}");
    let prefix = derive_prefix(name);
    let spec_comment = if spec_known {
        spec.to_string()
    } else {
        format!("{spec}  -- TODO: verify spec type path")
    };

    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.writeln(format!("-- {name} (BIJECTIVE — enum, unit constructors)"));
    w.writeln(format!("-- Extracted: {extracted}"));
    w.writeln(format!("-- Spec:      {spec_comment}"));
    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.newline();

    // toSpec
    w.writeln(format!("def {prefix}ToSpec : {extracted} → {spec}"));
    for v in variants {
        let vname = escape_lean_ident(&v.name);
        w.writeln(format!(
            "  | .{vname} => .{vname}  -- TODO: verify constructor name"
        ));
    }
    w.newline();

    // fromSpec
    w.writeln(format!("def {prefix}FromSpec : {spec} → {extracted}"));
    for v in variants {
        let vname = escape_lean_ident(&v.name);
        w.writeln(format!(
            "  | .{vname} => .{vname}  -- TODO: verify constructor name"
        ));
    }
    w.newline();

    // Roundtrip theorems
    w.writeln(format!("theorem {prefix}_roundtrip (s : {spec}) :"));
    w.writeln(format!("    {prefix}ToSpec ({prefix}FromSpec s) = s := by"));
    w.writeln("  cases s <;> rfl");
    w.newline();

    w.writeln(format!(
        "theorem {prefix}_roundtrip_inv (e : {extracted}) :"
    ));
    w.writeln(format!("    {prefix}FromSpec ({prefix}ToSpec e) = e := by"));
    w.writeln("  cases e <;> rfl");
    w.newline();

    // Equiv bundle
    w.writeln(format!("def {prefix}Equiv : {extracted} ≃ {spec} where"));
    w.writeln(format!("  toFun := {prefix}ToSpec"));
    w.writeln(format!("  invFun := {prefix}FromSpec"));
    w.writeln(format!("  left_inv := {prefix}_roundtrip_inv"));
    w.writeln(format!("  right_inv := {prefix}_roundtrip"));
    w.newline();
}

/// Emit INJECTIVE correspondence for an enum with data constructors.
fn emit_direct_injective(
    w: &mut IndentWriter,
    name: &str,
    namespace: &str,
    spec: &str,
    spec_known: bool,
    variants: &[ParsedVariant],
) {
    let extracted = format!("{namespace}.{name}");
    let prefix = derive_prefix(name);
    let spec_comment = if spec_known {
        spec.to_string()
    } else {
        format!("{spec}  -- TODO: verify spec type path")
    };

    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.writeln(format!(
        "-- {name} (INJECTIVE — enum with data constructors)"
    ));
    w.writeln(format!("-- Extracted: {extracted}"));
    w.writeln(format!("-- Spec:      {spec_comment}"));
    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.newline();

    // toSpec
    w.writeln(format!("def {prefix}ToSpec : {extracted} → {spec}"));
    for v in variants {
        let vname = escape_lean_ident(&v.name);
        if v.fields.is_empty() {
            w.writeln(format!("  | .{vname} => .{vname}  -- TODO: verify"));
        } else {
            let args: Vec<String> = (0..v.fields.len()).map(|i| format!("a{i}")).collect();
            let arg_str = args.join(" ");
            let mappings: Vec<String> = v
                .fields
                .iter()
                .enumerate()
                .map(|(i, f)| {
                    if rust_type_is_bounded_scalar(&f.ty) {
                        format!("a{i}.val")
                    } else {
                        format!("a{i}")
                    }
                })
                .collect();
            w.writeln(format!(
                "  | .{vname} {arg_str} => .{vname} {}  -- TODO: verify field mappings",
                mappings.join(" ")
            ));
        }
    }
    w.newline();

    // Injectivity theorem
    w.writeln(format!(
        "theorem {prefix}ToSpec_injective : Function.Injective {prefix}ToSpec := by"
    ));
    w.writeln("  intro x y h");
    w.writeln(format!(
        "  cases x <;> cases y <;> simp_all [{prefix}ToSpec]"
    ));
    w.writeln("  -- TODO: fill in remaining cases (use UScalar.eq_of_val_eq for bounded fields)");
    w.newline();
}

/// Emit RELATIONAL correspondence for a struct.
fn emit_direct_relational(
    w: &mut IndentWriter,
    name: &str,
    namespace: &str,
    spec: &str,
    spec_known: bool,
    fields: &[ParsedField],
    registry: &DirectRegistry,
) {
    let extracted = format!("{namespace}.{name}");
    let has_bounded = fields.iter().any(|f| rust_type_is_bounded_scalar(&f.ty));
    let strength_note = if has_bounded {
        "RELATIONAL — struct with bounded fields"
    } else {
        "RELATIONAL — struct"
    };
    let spec_comment = if spec_known {
        spec.to_string()
    } else {
        format!("{spec}  -- TODO: verify spec type path")
    };

    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.writeln(format!("-- {name} ({strength_note})"));
    w.writeln(format!("-- Extracted: {extracted}"));
    w.writeln(format!("-- Spec:      {spec_comment}"));
    w.writeln("-- ───────────────────────────────────────────────────────────────");
    w.newline();

    let struct_name = format!("{name}Corresponds");
    w.writeln(format!("structure {struct_name}"));
    w.writeln(format!("    (ec : {extracted})"));
    w.writeln(format!("    (sc : {spec}) : Prop where"));
    w.indent();
    for f in fields {
        let fname = escape_lean_keyword(&f.name);
        let eq_expr = direct_field_correspondence(&fname, &f.ty, registry);
        w.writeln(format!("{fname}_eq : {eq_expr}"));
    }
    w.dedent();
    w.newline();
}

/// Parse an existing BinaryBridge Lean file for `extracted_name → spec_path` mappings.
///
/// This is a standalone parser for use in direct mode (no charon_lib dependency).
/// It recognises the same two patterns as `bridge::parse_spec_map`:
///
/// ```text
/// def {name}ToSpec : Extracted.{ext} → {spec}
/// structure {name}Corresponds
///     (ec : Extracted.{ext})
///     (sc : {spec}) : Prop where
/// ```
pub fn parse_spec_map_direct(path: &Path) -> HashMap<String, String> {
    let content = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "styx: warning: cannot read spec-map file {}: {e}",
                path.display()
            );
            return HashMap::new();
        }
    };
    parse_spec_map_direct_str(&content)
}

fn parse_spec_map_direct_str(content: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let lines: Vec<&str> = content.lines().collect();

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Pattern 1: `def {name}ToSpec : Extracted.{ext} → {spec}`
        if line.starts_with("def ") && line.contains("ToSpec")
            && let Some(colon) = line.find(':') {
                let sig = line[colon + 1..].trim();
                if let Some(ext_name) = extract_extracted_name_direct(sig)
                    && let Some(spec) = extract_spec_path_from_arrow(sig) {
                        map.insert(ext_name, spec);
                    }
            }

        // Pattern 2: `structure {name}Corresponds` (multi-line)
        if line.starts_with("structure ") && line.contains("Corresponds") {
            let window: String = lines[i..lines.len().min(i + 5)]
                .iter()
                .map(|l| l.trim())
                .collect::<Vec<_>>()
                .join(" ");
            if let Some(ext_name) = extract_extracted_name_direct(&window)
                && let Some(spec) = extract_spec_path_from_sc(&window) {
                    map.insert(ext_name, spec);
                }
        }

        i += 1;
    }
    map
}

/// Extract simple extracted type name from `"Extracted.Foo → ..."` or `"... (ec : Extracted.Foo) ..."`.
fn extract_extracted_name_direct(s: &str) -> Option<String> {
    let prefix = "Extracted.";
    let start = s.find(prefix)? + prefix.len();
    let rest = &s[start..];
    let end = rest
        .find(|c: char| c.is_whitespace() || c == ')')
        .unwrap_or(rest.len());
    let name = rest[..end].trim().to_string();
    if name.is_empty() { None } else { Some(name) }
}

/// Extract spec path from `"Extracted.X → SpecPath"` or `"Extracted.X → SpecPath "`.
fn extract_spec_path_from_arrow(sig: &str) -> Option<String> {
    let arrow_pos = sig
        .find('→')
        .map(|p| (p, '→'.len_utf8()))
        .or_else(|| sig.find("->").map(|p| (p, 2)))?;
    let after = sig[arrow_pos.0 + arrow_pos.1..].trim();
    let end = after
        .find(|c: char| c.is_whitespace())
        .unwrap_or(after.len());
    let spec = after[..end].trim().to_string();
    if spec.is_empty() { None } else { Some(spec) }
}

/// Extract spec path from `"... (sc : SpecPath) ..."` or `"... (sx : SpecPath) ..."`.
fn extract_spec_path_from_sc(s: &str) -> Option<String> {
    let marker = s
        .find("sc :")
        .map(|p| (p, "sc :".len()))
        .or_else(|| s.find("sx :").map(|p| (p, "sx :".len())))?;
    let after = s[marker.0 + marker.1..].trim();
    let end = after
        .find(|c: char| c == ')' || c.is_whitespace())
        .unwrap_or(after.len());
    let spec = after[..end].trim().to_string();
    if spec.is_empty() { None } else { Some(spec) }
}

/// Emit a `Bridge_Template.lean` from directly-parsed Rust types.
///
/// Works without LLBC/Charon — operates purely on `ParsedCrate` types.
/// Classification logic:
/// - `RustEnum` with all unit variants → BIJECTIVE
/// - `RustEnum` with data variants    → INJECTIVE
/// - `RustStruct`                     → RELATIONAL
///
/// If `spec_map` is provided, spec type paths are resolved from the map
/// instead of using the heuristic `Lion.X` derivation.
pub fn emit_bridge_template_direct(
    parsed: &ParsedCrate,
    namespace: &str,
    spec_map: Option<&HashMap<String, String>>,
) -> String {
    let rules = RewriteRules::standard();
    let mut w = IndentWriter::new();

    // Preamble
    w.writeln("-- ═══════════════════════════════════════════════════════════════");
    w.writeln("-- Bridge Template: auto-generated correspondence proof outlines.");
    w.writeln("-- Generated by Styx (direct mode). Fill in proof bodies.");
    w.writeln("-- ═══════════════════════════════════════════════════════════════");
    w.newline();
    w.writeln(format!("import {namespace}.Types"));
    w.writeln("-- TODO: import your spec types (e.g., import Lion.Core.Types)");
    w.newline();
    w.writeln("set_option linter.dupNamespace false");
    w.writeln("set_option linter.unusedVariables false");
    w.newline();
    w.writeln(format!("namespace {namespace}.Bridge"));
    w.newline();

    // Filter types: skip std/core/alloc and aliases.
    let types: Vec<&ParsedTypeDef> = parsed
        .types
        .iter()
        .filter(|t| {
            !t.name.starts_with("std.")
                && !t.name.starts_with("core.")
                && !t.name.starts_with("alloc.")
        })
        .collect();

    // Build registry: simple_name → DirectBridgeKind (for field correspondence lookups).
    let mut registry: DirectRegistry = HashMap::new();
    for def in &types {
        if let Some(kind) = classify_direct(def) {
            registry.insert(def.simple_name.clone(), kind);
        }
    }

    let mut count_bijective = 0u32;
    let mut count_injective = 0u32;
    let mut count_relational = 0u32;

    for def in &types {
        let bridge_kind = match classify_direct(def) {
            Some(k) => k,
            None => continue,
        };

        let name = &def.simple_name;
        let (spec, spec_known) = derive_direct_spec_name(name, spec_map);

        // Emit generic-params comment if type has parameters (bridge doesn't support generics yet).
        if !def.type_params.is_empty() {
            w.writeln(format!(
                "-- NOTE: {name} has generic params {:?} — bridge template is monomorphised. Adjust as needed.",
                def.type_params
            ));
        }

        match bridge_kind {
            DirectBridgeKind::Bijective => {
                if let ParsedTypeKind::Enum(variants) = &def.kind {
                    emit_direct_bijective(&mut w, name, namespace, &spec, spec_known, variants);
                    count_bijective += 1;
                }
            }
            DirectBridgeKind::Injective => {
                if let ParsedTypeKind::Enum(variants) = &def.kind {
                    emit_direct_injective(&mut w, name, namespace, &spec, spec_known, variants);
                    count_injective += 1;
                }
            }
            DirectBridgeKind::Relational => {
                if let ParsedTypeKind::Struct(fields) = &def.kind {
                    emit_direct_relational(
                        &mut w, name, namespace, &spec, spec_known, fields, &registry,
                    );
                    count_relational += 1;
                }
            }
        }
    }

    // Drop unused `rules` — it's needed only for type printing (not used in bridge output here).
    drop(rules);

    eprintln!(
        "styx bridge (direct): {} types scanned, {} emitted ({} bijective, {} injective, {} relational)",
        types.len(),
        count_bijective + count_injective + count_relational,
        count_bijective,
        count_injective,
        count_relational
    );

    // Summary
    w.writeln("-- ═══════════════════════════════════════════════════════════════");
    w.writeln(format!(
        "-- Summary: {} BIJECTIVE, {} INJECTIVE, {} RELATIONAL",
        count_bijective, count_injective, count_relational
    ));
    w.writeln(format!(
        "-- Total: {} type correspondences",
        count_bijective + count_injective + count_relational
    ));
    w.writeln("-- ═══════════════════════════════════════════════════════════════");
    w.newline();

    w.writeln(format!("end {namespace}.Bridge"));

    w.finish()
}
