//! Lean → Rust skeleton emitter.
//!
//! Reads parsed Lean type definitions and emits Rust struct/enum skeletons.
//! This is the `--lean-to-rust` mode emission backend.
//!
//! Type mapping (Lean → Rust):
//! - `Nat`        → `u64`        (comment: "Lean: Nat (bounded by u64)")
//! - `Bool`       → `bool`
//! - `String`     → `String`
//! - `Int`        → `i64`
//! - `Fin n`      → `u64`
//! - `List T`     → `Vec<T>`
//! - `Finset T`   → `Vec<T>`     (comment: "Lean: Finset T")
//! - `Option T`   → `Option<T>`
//! - `Array T n`  → `Vec<T>`
//! - `ByteArray`  → `Vec<u8>`
//! - Unknown T    → T            (comment: "TODO: map Lean type T")

use crate::lean_parser::{LeanField, LeanTypeDef, LeanVariant};

/// Emit Rust skeleton source for a slice of parsed Lean type definitions.
///
/// The `module_path` is used as the doc-comment provenance hint (e.g.
/// `Lion.Core.Policy`). Pass an empty string to omit path hints.
pub fn emit_rust_skeletons(defs: &[LeanTypeDef], module_path: &str) -> String {
    let mut out = String::new();

    out.push_str("// This file was generated by styx --lean-to-rust.\n");
    out.push_str("// Do not edit manually.\n");
    out.push('\n');
    out.push_str("#![allow(dead_code)]\n");
    out.push('\n');

    for def in defs {
        match def {
            LeanTypeDef::Structure { name, fields } => {
                emit_struct(&mut out, name, fields, module_path);
                out.push('\n');
            }
            LeanTypeDef::Inductive { name, variants } => {
                emit_enum(&mut out, name, variants, module_path);
                out.push('\n');
            }
        }
    }

    out
}

// ---------------------------------------------------------------------------
// Internal emitters
// ---------------------------------------------------------------------------

/// Emit a Rust `pub struct` for a Lean `structure`.
fn emit_struct(out: &mut String, name: &str, fields: &[LeanField], module_path: &str) {
    push_doc_comment(out, name, "structure", module_path);
    out.push_str(&format!("pub struct {name} {{\n"));
    for field in fields {
        let (rust_ty, comment) = map_lean_type(&field.lean_type);
        let comment_str = comment
            .map(|c| format!("  // Lean: {}", c))
            .unwrap_or_default();
        out.push_str(&format!(
            "    pub {}: {},{}\n",
            rust_field_name(&field.name),
            rust_ty,
            comment_str
        ));
    }
    out.push_str("}\n");
}

/// Emit a Rust `pub enum` for a Lean `inductive`.
fn emit_enum(out: &mut String, name: &str, variants: &[LeanVariant], module_path: &str) {
    push_doc_comment(out, name, "inductive", module_path);
    out.push_str(&format!("pub enum {name} {{\n"));
    for variant in variants {
        emit_variant(out, variant);
    }
    out.push_str("}\n");
}

/// Emit a single enum variant.
fn emit_variant(out: &mut String, variant: &LeanVariant) {
    if variant.fields.is_empty() {
        out.push_str(&format!("    {},\n", variant.name));
    } else if variant.fields.len() == 1 && variant.fields[0].name.starts_with("__anon") {
        // Anonymous single-field variant: use newtype style
        let (rust_ty, _) = map_lean_type(&variant.fields[0].lean_type);
        out.push_str(&format!("    {}({}),\n", variant.name, rust_ty));
    } else {
        // Named fields — struct variant
        out.push_str(&format!("    {} {{\n", variant.name));
        for field in &variant.fields {
            let (rust_ty, comment) = map_lean_type(&field.lean_type);
            let comment_str = comment
                .map(|c| format!("  // Lean: {}", c))
                .unwrap_or_default();
            out.push_str(&format!(
                "        {}: {},{}\n",
                rust_field_name(&field.name),
                rust_ty,
                comment_str
            ));
        }
        out.push_str("    },\n");
    }
}

/// Emit the `/// Corresponds to: ...` doc comment.
fn push_doc_comment(out: &mut String, name: &str, kind: &str, module_path: &str) {
    if module_path.is_empty() {
        out.push_str(&format!("/// Lean {kind}: {name}\n"));
    } else {
        out.push_str(&format!("/// Corresponds to: {module_path}.{name}\n"));
    }
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

/// Map a Lean type string to `(rust_type, optional_comment)`.
///
/// The comment is set for types that lose information (e.g. `Nat` → `u64`).
pub fn map_lean_type(lean_ty: &str) -> (String, Option<String>) {
    let trimmed = lean_ty.trim();

    // Exact matches first
    match trimmed {
        "Nat" => return ("u64".to_string(), Some("Nat (bounded by u64)".to_string())),
        "Bool" => return ("bool".to_string(), None),
        "String" => return ("String".to_string(), None),
        "Int" => return ("i64".to_string(), None),
        "ByteArray" => return ("Vec<u8>".to_string(), None),
        "Unit" => return ("()".to_string(), None),
        _ => {}
    }

    // `Fin n` → `u64`
    if trimmed.starts_with("Fin ") || trimmed.starts_with("Fin(") {
        return ("u64".to_string(), Some(trimmed.to_string()));
    }

    // `List T` → `Vec<T>`
    if let Some(inner) = strip_prefix_type(trimmed, "List") {
        let (inner_rust, _) = map_lean_type(inner);
        return (format!("Vec<{inner_rust}>"), None);
    }

    // `Finset T` → `Vec<T>` with comment
    if let Some(inner) = strip_prefix_type(trimmed, "Finset") {
        let (inner_rust, _) = map_lean_type(inner);
        return (
            format!("Vec<{inner_rust}>"),
            Some(format!("Finset {inner_rust}")),
        );
    }

    // `Option T` → `Option<T>`
    if let Some(inner) = strip_prefix_type(trimmed, "Option") {
        let (inner_rust, _) = map_lean_type(inner);
        return (format!("Option<{inner_rust}>"), None);
    }

    // `Array T n` → `Vec<T>` (drop size)
    if trimmed.starts_with("Array ") {
        let rest = trimmed["Array ".len()..].trim();
        // rest is "T n" — take the first token as T
        let type_part = rest.split_whitespace().next().unwrap_or(rest);
        let (inner_rust, _) = map_lean_type(type_part);
        return (format!("Vec<{inner_rust}>"), None);
    }

    // Unknown — emit as-is with TODO comment
    let rust_name = lean_type_to_rust_ident(trimmed);
    (rust_name, Some(format!("TODO: map Lean type '{trimmed}'")))
}

/// Strip a type constructor prefix: `List T` → `Some("T")`.
///
/// Handles both `Con T` (space-separated) and `Con(T)` (paren) forms.
fn strip_prefix_type<'a>(s: &'a str, prefix: &str) -> Option<&'a str> {
    if let Some(rest) = s.strip_prefix(prefix) {
        let rest = rest.trim_start();
        if rest.starts_with('(') && rest.ends_with(')') {
            Some(rest[1..rest.len() - 1].trim())
        } else if !rest.is_empty()
            && (rest.starts_with(|c: char| c.is_alphanumeric() || c == '_' || c == '('))
        {
            Some(rest)
        } else {
            None
        }
    } else {
        None
    }
}

/// Convert an unknown Lean type name to a plausible Rust identifier.
///
/// Lean uses CamelCase; that maps directly to Rust. Spaces become underscores.
fn lean_type_to_rust_ident(lean: &str) -> String {
    // If it looks like a generic application (contains space), take first token
    let first = lean.split_whitespace().next().unwrap_or(lean);
    first.to_string()
}

/// Sanitize a Lean field name to a valid Rust identifier.
///
/// Lean fields are generally valid Rust identifiers. We escape Rust keywords.
fn rust_field_name(name: &str) -> String {
    match name {
        "type" | "ref" | "move" | "in" | "use" | "mod" | "fn" | "let" | "match" | "loop"
        | "for" | "if" | "else" | "while" | "return" | "break" | "continue" | "struct" | "enum"
        | "impl" | "trait" | "where" | "pub" | "super" | "self" | "Self" | "crate" | "static"
        | "const" | "mut" | "unsafe" | "extern" | "dyn" | "async" | "await" | "true" | "false"
        | "as" | "box" | "yield" | "abstract" | "become" | "final" | "override" | "priv"
        | "typeof" | "unsized" | "virtual" | "do" | "try" => {
            format!("{name}_")
        }
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_lean_nat() {
        let (ty, comment) = map_lean_type("Nat");
        assert_eq!(ty, "u64");
        assert!(comment.unwrap().contains("bounded by u64"));
    }

    #[test]
    fn test_map_lean_finset() {
        let (ty, comment) = map_lean_type("Finset Right");
        assert_eq!(ty, "Vec<Right>");
        assert!(comment.unwrap().contains("Finset"));
    }

    #[test]
    fn test_map_lean_option() {
        let (ty, comment) = map_lean_type("Option String");
        assert_eq!(ty, "Option<String>");
        assert!(comment.is_none());
    }

    #[test]
    fn test_map_lean_list() {
        let (ty, _) = map_lean_type("List Nat");
        assert_eq!(ty, "Vec<u64>");
    }

    #[test]
    fn test_map_lean_byte_array() {
        let (ty, _) = map_lean_type("ByteArray");
        assert_eq!(ty, "Vec<u8>");
    }

    #[test]
    fn test_rust_field_name_escaping() {
        assert_eq!(rust_field_name("type"), "type_");
        assert_eq!(rust_field_name("subject"), "subject");
        assert_eq!(rust_field_name("r#type"), "r#type");
    }
}
